# Generated by Django 4.1.5 on 2023-01-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="watch",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="WATCH"),
        ),
    ]
