# Generated by Django 4.1.5 on 2023-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_watch"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="image",),
        migrations.AddField(
            model_name="comment",
            name="nickname",
            field=models.CharField(
                default="hi", max_length=20, null=True, verbose_name="NICKNAME"
            ),
        ),
    ]
